name: ytquran
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-120.0.dev <3.0.0'

dependencies:

  flutter:
    sdk: flutter 
  connectivity: ^3.0.6
  flutter_launcher_icons: ^0.11.0
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.5
  geolocator: ^9.0.2
  go_router: ^6.0.1
  http: ^0.13.5
  lottie: ^2.2.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  flutter_lints: ^2.0.1
  counter_button: ^1.0.1
  intl: ^0.18.0
  syncfusion_flutter_datepicker: ^21.1.39
  scrollable_positioned_list: ^0.2.3
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.15
  share_plus: ^4.0.3
  url_launcher: ^6.1.6
  simple_animations: ^5.0.0+3
  colorful_background: ^0.0.4
  animated_background: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.0.1
  custom_lint: ^0.2.11 
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/quran.png
  android: true
  ios: true
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: quran
      fonts:
        - asset: assets/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/me_quran.ttf
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/IBMPlexSansArabic-Regular.ttf    
